version: '3'
services:

    # backend
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        # environment:
        #     MONGODB_HOST: mongodb
        #     MONGODB_USERNAME: "apiuser"
        #     MONGODB_PASSWORD: "apipassword"
        volumes:
            - appdata:/var/www/
        # depends_on: 
        #     - mongodb
        networks:
            - frontend
            - backend
        
    
    
    # frontend
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./client:/app
            - /app/node_modules
        networks:
            - frontend


networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    # mongodbdata:
    #     driver: local
    appdata:
        driver: local